language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
  - shards
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_SHARDS_DIR=shards
  - BINARYBUILDER_AUTOMATIC_APPLE=true
  - BINARYBUILDER_USE_CCACHE=true
sudo: required
before_script:
- julia -e 'using Pkg; pkg"add BinaryProvider"; pkg"add BinaryBuilder#master"; Pkg.build()'
script:
- julia build_tarballs.jl
deploy:
  provider: releases
  api_key:
    secure: MZWL7dQRCaHKo2pMdPvpTtgvB0MBcSYQdpU/qHW/gvh5PN4SaDiTBkArcpD6W+M2fJUQd9QIcrkgv22QGRKB5fCaxq79FIyd7P7Lt0MgpZyQ4cqZvyPGe9ZLqUszCd/yrWiqCqKxVvBE/XA33kTBzLGwOG7ff1JnAQim2SYMsXxBQygamyh4CyKYpnywM0UnBCWdRb+22HBW4qtPQMCILnI8IAlgSFky2zv0uvG8IGJYC3+I8fLZkd6EkPcJ0zUdC16hSv+SDRYcmC0j5KX2K2v3fQOTY2zqDCWDRvvvFrvpfHXK8MekFNtMR+ZEBi+S76T2LNh4PEJgY4E5CQiJpRVyn1NNWSyITRFYK2rJhBPPnuroG25OiHd5AGZuKhjWyA/E6jkB3wzWxRSLJ5n5fMdF29D8/sF5oslwkpGxf5T7NEpvIoZeVVu6FpavNkJim4FewZHtUyXv0bDQdeuMuRE/tfghc8pgcei6DJo1rwx2oDgFNaCFISj0Y0vZS+KosXWJp4ICpN/RAtNnQrSSlZNcuqBZ7rifxoHSowX7g5Fg4VZXg5yGQEk0b/SebpkPIWQSq4SbRbjP9QriOoZ+jQPwlBhNIF9r/eoapFgmzcCS9YijJ0KU/+MNZvQTdGtwjkg0L14EXlh94e89O8Xsfum2EC3TwZyq0UVq40dlR1E=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: ianshmean/Frei0rBuilder
  api-key:
    secure: Nm/cJJJstUKsS5g2n55WmNC5GuMoNVWHAGfevUnywHvIFHiDxFmXtoiRhFGvT28mhKL7+Qq51UbG0wyJwf3kqiMFJ34XnBhffn8DQSxigvJuUyxHEu0I4xdOXVIx9BK0MsCOutijP+erC9AYmAReXP9Zf7ilbqpWTBW7QxdRauMhvJuO0lyPxlibiMgcKe3dV4DshvpbFTwm7123mtpsUTfRL8i1NyKno1xb7eKwVGWvOFsjuUVZ4gIkaCzA3zNdhsB8zDL9bmuX9jrPYptaTVFt28SCfd1lgG30R0OwdEmKqAzDodLWU4upjO+ToiWlZ6e3L7NWli3LTN5NgiS006rOXimFBr9CKJwcUiwMGcBxZaSo0wHRjaKl0yPpb+cgXL5kWEGLM6xbkntZlpaUQkK37+m/jdgVIWmn8RWn47d9J1H1DeEDnrfMznj3sjsBG5wXp9dCRqOTPNy24URUYC3EK85IL722wu8Pzdmkkgf1VvS1qv8N13BCb6WB7LmdH8k7FYALerhs+gid8rDh3ufuEHn61HifxH8VKO2XUWzhc3k5Mz5dXhejzOxW+nYoVZEksJ+kz1ebfJQZf2O7cAHQREwYoRFgsY2sH+AIQk8VCcdjr//XKu9twO2CSN9MIaYHw7iVl4iYKMsNgd6Duuz0+mYNUWoN1OkvGCy/+ho=
